# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  # jwt token auth
  # Add somewhere to your secrets yml
  # "config/secrets.yml"
  jwt_secret: '38af0483c50d39ebd0b58ea81a3fc366c1995c4da5bsuperrandomkey'
  jwt_expiration_hours: 18
  
  secret_key_base: 8ef451c381bb731dea9b1d70eb30933d3be13a1f66b4ed01cee906b7e2e397f6faf58c9e9dd12ce2f33c34eeef52df50ea090267c96a845811d504b2f85db4ab

test:
  secret_key_base: e21035451cc2c2557858c2e08e66feebabcc64adc205adb54df17dd453768622ef08030dd69e32da9f239898f8651cd51c0d34f20b390833034cf8da33ede73f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

  # jwt token auth
  # Add somewhere to your secrets yml
  # "config/secrets.yml"
  jwt_secret: '62d2f8f20c9852a2da46b9332c8ec62ba95d82509a7c758evenmoresuperrandomkey'
  jwt_expiration_hours: 18
  
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
